run:
  timeout: 5m
  tests: false
linters:
   enable-all: true
   disable:
     - cyclop
     - exportloopref
     - depguard
     - exhaustruct
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godox
     - godot
     - err113
     - gofumpt
     - mnd
     - lll
     - musttag
     - nakedret
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
